[Variables]


Hidden=1
Hidden2=0
Player=Spotify
Color2=247,194,134

WeatherLocation=Amritsar
; Just enter your city's name or your address here or whatever. Anything should work here.
; TIP: Check Rainmeter's log to see what location it got.

WeatherUnits=Metric
; The units of the weather info. Valid values are "Metric" and "Imperial".

Language=en
; The language code for the weather information. Most languages are supported, but it's not guaranteed to work.
; Recommended and working values are (kind of grouped by area):
; "en" (English),
; "de" (German), "nl" (Dutch), "fr" (French), "es" (Spanish), "pt" (Portuguese), "it" (Italian),
; "sv" (Swedish), "no" (Norwegian), "fi" (Finnish), "da" (Danish),
; "ar" (Arabic), "tr" (Turkish),"hr" (Croatian), "el" (Greek), "cs" (Czech),
; "ru" (Russian), "pl" (Polish), "ro" (Romanian), "sk" (Slovak), "uk" (Ukrainian),"et" (Estonian), "hu" (Hungarian),
; "zh" (Chinese),"ja" (Japanese), "ko" (Korean), "th" (Thai), "vi" (Vietnamese), "hi" (Hindi), "bn" (Bangla).

; ================================================

24HTime=True
; Enable or disable 24-hour time.
; Valid values are "True" and "False".

; ================================================

Font=Roboto
; The font used in the skin.


Color1=FFFFFF

FONTCOLOR=102,63,15,255

Color=255, 255, 255
; The color of the text and the Mono icons.
; Valid values are formatted "RRR, GGG, BBB" with values of 0-255.

IconStyle=Color
BORDER=ffffff
; The style of the weather icons. Valid values are "Color" and "Mono".
; The Mono icons are embedded in the JDWI.ttf font and the Color icons are found in "@Resources\WeatherIcons".
