[Variables]

Language=
UnitOfMeasure=m
ScrollMouseIncrement=0.01
Format=H
Hidden=0
Hidden2=1
Player=Spotify
Color1=191,191,191
Color2=77,128,211
Color3=191,191,191
Color4=191,191,191
Color5=77,128,211
Color6=191,191,191
Color7=77,128,211
Color8=191,191,191
Color9=77,128,211
Color10=191,191,191
Color11=77,128,211
Color12=191,191,191
Color13=77,128,211

;----------------------Icon Dock Settings--------------------------
;------------------------------------------------------------------


Icon1NameAndPath=#@#\01.png
LocationPath1=

Icon2NameAndPath=#@#\02.png
LocationPath2=

Icon3NameAndPath=#@#\03.png
LocationPath3=

Icon4NameAndPath=#@#\04.png
LocationPath4=

Icon5NameAndPath=#@#\05.png
LocationPath5=

Icon6NameAndPath=#@#\06.png
LocationPath6=

Icon7NameAndPath=#@#\07.png
LocationPath7=

Icon8NameAndPath=#@#\08.png
LocationPath8=

Icon9NameAndPath=#@#\09.png
LocationPath9=

Icon10NameAndPath=#@#\10.png
LocationPath10=

;----------------------Link Dock Settings--------------------------
;------------------------------------------------------------------

Name1=Google
Link1=chrome.exe

Name2=Facebook
Link2=https://facebook.com/

Name3=Twitter
Link3=https://twitter.com/

Name4=YouTube
Link4=https://www.youtube.com/

Name5=Behance
Link5=https://www.behance.net/

Name6=Gmail
Link6=https://mail.google.com/mail/

Name7=Deviantart
Link7=https://www.deviantart.com/popular-24-hours/

